# These are flags you must include - Two memory and one runtime.
# Runtime is either seconds or hours:min:sec

#$ -wd /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/
#$ -l tmem=20G
#$ -l h_rt=4:00:00

#These are optional flags but you probably want them in all jobs

#$ -S /bin/bash
##$ -j y
#$ -N maml_meta_testing

# A double hash comments out the scheduler directive

#$ -t 1-26

#$ -l gpu=true
##$ -R y

#The code you want to run now goes here.

# function finish {
#     rm -rf /scratch0/apappu/$JOB_ID
# }

# trap finish EXIT ERR

hostname
# date
# uname -r
# nvidia-smi

source /share/apps/source_files/python/python-3.6.4.source
export PATH="/share/apps/git-2.9.5/bin:$PATH" # ensure we are using the correct git version for chemprop
# conda activate chemprop


# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1614170 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1614170 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1614170.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1614202 --dataset_type classification  --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1614202 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1614202.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1614359 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1614359 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1614359.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1738019 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1738019 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1738019.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 2 3 4 5 7 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1738021 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1738021 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1738021.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1738131 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1738131 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1738131.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 3 4 7 10 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1738202 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1738202 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1738202.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1794355 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1794355 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1794355.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 1 4 5 6 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1794358 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1794358 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1794358.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1794567 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1794567 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1794567.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909085 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909085 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909085.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909092 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909092 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909092.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 8 10 17 23 24  --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909192 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909192 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909192.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909209 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909209 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909209.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909211 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909211 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909211.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1909212 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1909212 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1909212.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1963705 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1963705 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1963705.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1963741 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1963741 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1963741.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 0 4 5 6 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL1963934 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL1963934 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL1963934.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL2028077 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL2028077 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL2028077.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 2 3 7 8 9 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL2095143 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL2095143 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL2095143.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL2098499 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL2098499 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL2098499.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL2114797 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL2114797 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL2114797.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL3215116 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL3215116 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL3215116.log 2>&1
 
# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 1 2 4 5 6 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL3215176 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL3215176 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL3215176.log 2>&1

# python /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/chemprop/meta_test.py --seeds 1 3 4 6 7 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --meta_test_task CHEMBL918058 --dataset_type classification --chembl_assay_metadata_pickle_path filtered_chembl/ --checkpoint_paths checkpoints/maml/fold_0/maml_model/maml_maml_model.pt --save_dir checkpoints/metatesting/maml/ --metric 'prc-auc' --split_type scaffold_balanced  --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/metatesting/maml/ --experiment_name maml_CHEMBL918058 > /home/apappu/thesis/molecule-metalearning2/molecule-metalearning/jobs/logs/metatesting/maml/CHEMBL918058.log 2>&1

