source /share/apps/source_files/python/python-3.6.4.source
export PATH="/share/apps/git-2.9.5/bin:$PATH" # ensure we are using the correct git version for chemprop

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614170 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1614170 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1614170.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614202 --dataset_type classification  --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1614202 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1614202.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614359 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1614359 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1614359.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738019 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1738019 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1738019.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 2 3 4 5 7 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738021 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1738021 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1738021.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738131 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1738131 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1738131.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 3 4 7 10 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738202 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1738202 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1738202.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794355 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1794355 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1794355.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 1 4 5 6 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794358 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1794358 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1794358.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794567 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1794567 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1794567.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909085 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909085 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909085.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909092 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909092 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909092.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 8 10 17 23 24  --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909192 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909192 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909192.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909209 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909209 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909209.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909211 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909211 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909211.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909212 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1909212 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1909212.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963705 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1963705 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1963705.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963741 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1963741 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1963741.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 0 4 5 6 12 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963934 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL1963934 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL1963934.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2028077 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL2028077 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL2028077.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 2 3 7 8 9 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2095143 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL2095143 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL2095143.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2098499 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL2098499 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL2098499.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2114797 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL2114797 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL2114797.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL3215116 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL3215116 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL3215116.log 2>&1
 
python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 1 2 4 5 6 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL3215176 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL3215176 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL3215176.log 2>&1

python /home/apappu/thesis/molecule-metalearning/chemprop/train.py --seeds 1 3 4 6 7 --data_path /home/apappu/thesis/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL918058 --dataset_type classification --metric 'prc-auc' --split_type scaffold_balanced --features_only --features_generator morgan --dropout 0.2 --ffn_hidden_size 400 --num_folds 5 --epochs 30 --num_workers 0 --results_save_dir results/ecfp_single_task_on_test_tasks/ --experiment_name CHEMBL918058 > /home/apappu/thesis/molecule-metalearning/jobs/logs/ecfp_single_task/CHEMBL918058.log 2>&1

