# These are flags you must include - Two memory and one runtime.
# Runtime is either seconds or hours:min:sec

#$ -wd /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/
#$ -l tmem=20G
#$ -l h_rt=24:00:00

#These are optional flags but you probably want them in all jobs

#$ -S /bin/bash
##$ -j y
#$ -N finetuning_experiment

# A double hash comments out the scheduler directive

#$ -t 1-26

#$ -l gpu=true
##$ -R y

#The code you want to run now goes here.

# function finish {
#     rm -rf /scratch0/apappu/$JOB_ID
# }

# trap finish EXIT ERR

# export PATH="/share/apps/git-2.9.5/bin:$PATH" # ensure we are using the correct git version for chemprop

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614170 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1614170_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1614170_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614202 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1614202_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1614202_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1614359 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1614359_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1614359_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738019 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1738019_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1738019_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 2 3 4 5 7 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738021 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1738021_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1738021_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738131 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1738131_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1738131_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 3 4 7 10 12 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1738202 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1738202_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1738202_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794355 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1794355_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1794355_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 1 4 5 6 12 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794358 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1794358_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1794358_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1794567 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1794567_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1794567_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909085 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909085_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909085_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909092 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909092_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909092_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 8 10 17 23 24 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909192 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909192_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909192_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909209 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909209_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909209_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909211 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909211_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909211_test_task.log 2>&1 
 
# python chemprop/finetune.py  --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1909212 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1909212_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1909212_test_task.log 2>&1 
# for task above, --seeds 0 2 5 6 7
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963705 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1963705_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1963705_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963741 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL1963741_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL1963741_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 0 4 5 6 12 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL1963934 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/outputs/pretraining/fold_0/model_0/pretraining_0.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_0/ --experiment_name finetuning_on_CHEMBL1963934_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_0/finetuning_on_CHEMBL1963934_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2028077 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL2028077_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL2028077_test_task.log 2>&1 
 
# python chemprop/finetune.py --seeds 2 3 7 8 9 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2095143 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL2095143_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL2095143_test_task.log 2>&1 

# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2098499 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL2098499_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL2098499_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL2114797 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL2114797_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL2114797_test_task.log 2>&1 
 
# python chemprop/finetune.py --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL3215116 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL3215116_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL3215116_test_task.log 2>&1 
 
python chemprop/finetune.py --seeds 1 2 4 5 6 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL3215176 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL3215176_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL3215176_test_task.log 2>&1 

python chemprop/finetune.py --seeds 1 3 4 6 7 --data_path /home/azureuser/molecule-metalearning/filtered_chembl/chembl_less_1024_more_128_645_tasks.csv --target_columns CHEMBL918058 --dataset_type classification --split_type scaffold_balanced --checkpoint_paths /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/checkpoints/fold_0/model_0/pretraining_1.pt --num_folds 5 --epochs 30 --results_save_dir results/finetuning/pretraining_1/ --experiment_name finetuning_on_CHEMBL918058_test_task > /home/azureuser/molecule-metalearning-finetuning/molecule-metalearning/jobs/logs/finetuning/pretraining_1/finetuning_on_CHEMBL918058_test_task.log 2>&1 
